name: "appflowy_editor"

version: 4.0.0

homepage: "https://github.com/AppFlowy-IO/appflowy-editor"

environment:
  sdk: ">=3.0.2 <4.0.0"

description: A highly customizable rich-text editor for Flutter. The AppFlowy
  Editor project for AppFlowy and beyond.

dependencies:
  device_info_plus: ^11.1.1
  diff_match_patch: ^0.4.1
  file_picker: ^8.1.4  
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.14
  html: any
  http: "^1.2.0"                      
  intl: any               
  keyboard_height_plugin: any
  logging: "^1.1.0"                   
  markdown: "^4.0.0"                  
  nanoid: any                 
  numerus: "^2.2.0"                   
  pdf: ^3.11.0                    
  provider: ^6.1.2
  scroll_to_index: "^3.0.1"           
  string_validator: "^1.0.0"          
  universal_html: ^2.2.4           
  universal_platform: ^1.1.0
  url_launcher: "^6.1.12"             

dev_dependencies:
  flutter_lints: ^4.0.0              
  flutter_localizations:
    sdk: flutter 
  flutter_test:
    sdk: flutter
  intl_utils: any              
  mockito: ^5.4.2                   
  network_image_mock: ^2.1.1         
  path_provider: ^2.0.11           
  pubspec_dependency_sorter: ^1.0.5  

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:

topics:
  - ui
  - widgets
  - editor
  - appflowy

flutter:
  assets:
    - "assets/images/toolbar/"
    - "assets/images/selection_menu/"
    - "assets/images/image_toolbar/"
    - "assets/images/"
    - "assets/mobile/toolbar_icons/"

flutter_intl:
  enabled: true
  class_name: AppFlowyEditorLocalizations
  main_locale: en
  arb_dir: lib/l10n
  output_dir: lib/src/l10n
  use_deferred_loading: false
  localizely:
    project_id: b7199c7d-eca0-4025-894d-230cdcafa9aa
